name: weather_app
description: My Weather app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  bloc: ^8.1.0
  dartz: ^0.10.1
  dio: ^4.0.6
  envied: ^0.2.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  intl: ^0.17.0
  logger: ^1.1.0
  shimmer: ^2.0.0


dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  envied_generator: ^0.2.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/